services:
  db:
    image: mysql:latest
    restart: no
    environment:
      MYSQL_DATABASE: "testdb"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: toan
      # You can use whatever password you like
      MYSQL_PASSWORD: ductoan0712
      # Password for root access
      MYSQL_ROOT_PASSWORD: root
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - "./docker/db/data:/var/lib/mysql"
# Names our volume
volumes:
  my-db:
